### ISSUE TITLE
cgogen does not generate anything

### ISSUE THREAD

**Issue by deepakjois** [xlab/cgogen#3]
See deepakjois/harfbuzz-go@551508ac14326288e0821e5d52bd8fb71cfe06bd

The files are empty except some boilerplate code. Could you please suggest what I need to try to fix it. Do I have to include more header files in the `SourcesPaths` key?

**Comment by xlab** [comment]
Like I suggested in comments to your commit, you should include `TRANSLATOR` rules that would accept all methods and types. Everything is ignored by default.

```
TRANSLATOR: 
  ConstRules: 
    defines: expand
  Rules: 
    global: 
      - {transform: lower}
      - {action: accept, from: "^hb_"}
      - {action: replace, from: "^hb_", to: _}
      - {transform: export}
    const:
      - {action: accept, from: "^HB_"}
      - {action: replace, from: "^hb_", to: _}
    type: 
      - {action: replace, from: "_t$"}
    private:
      - {transform: unexport}
    post-global: 
      - {action: replace, from: _$}
      - {load: snakecase}
```

Everything seems alright then. After that you'l' be able to specify PtrTips for the methods.
Consult the documentation for that https://github.com/xlab/cgogen/wiki/Translator-config-section.
