### ISSUE TITLE
Incorrect line number reported during YAML parsing

### ISSUE THREAD

**Issue by deepakjois** [xlab/cgogen#6]
``` yaml

---
GENERATOR:
  PackageName: cgogentest
  PackageDescription: "Package harfbuzz provides Go bindings for Harfbuzz"
  PackageLicense: "THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS."
  PkgConfigOpts: [harfbuzz]
  Includes: [hb.h]

PARSER:
  IncludePaths:
    - /usr/include
  SourcesPaths:
    - cgogentest/cgogentest.h

TRANSLATOR:
  ConstRules:
    defines: expand
  PtrTips:
    function:
      - {target: "_buffer_serialize_list_formats$", self: arr, tips: [ref]}
      - {target: ".", tips:[sref,sref,sref,sref,sref]}
  Rules:
    global:
      - {transform: lower}
      - {action: accept, from: "^hb_"}
      - {action: replace, from: "^hb_", to: _}
      - {transform: export}
    const:
      - {action: accept, from: "^HB_"}
      - {action: replace, from: "^hb_", to: _}
    type:
      - {action: ignore, from: "_func_t$"}
      - {action: replace, from: "_t$"}
    private:
      - {transform: unexport}
    post-global:
      - {action: replace, from: _$}
      - {load: snakecase}
```

Reports an error:

```
17:18 $ cgogen cgogentest.yml
  processing cgogentest.yml ⠋[ERR] yaml: line 20: found unexpected ':'
```

It took me 5 minutes to realise that the error is actually on Line 21

```
      - {target: ".", tips:[sref,sref,sref,sref,sref]}
```
