### ISSUE TITLE
cgo_helpers.h wont compile

### ISSUE THREAD

**Issue by proglottis** [xlab/cgogen#8]
I found a case in gpgme that doesn't seem to generate cgo_helpers.h quite right. I've created a minimal example of it (no dependence on gpgme) to demonstrate.

gpgme.yml:
```yaml
---
GENERATOR:
  PackageName: gpgme
  Includes: ["gpgme.h"]
PARSER:
  SourcesPaths: ["gpgme.h"]
TRANSLATOR:
  Rules:
    global:
      - {action: accept, from: "^gpgme_"}
```

gpgme.h:
```c
typedef unsigned int gpg_error_t;
typedef gpg_error_t gpgme_error_t;
typedef gpgme_error_t (*gpgme_io_cb_t) (void *data, int fd);
typedef gpgme_error_t (*gpgme_register_io_cb_t) (void *data, int fd, int dir,
						 gpgme_io_cb_t fnc,
						 void *fnc_data, void **tag);
```

And here's the error:
```
$ rm -rf gpgme/ && cgogen gpgme.yml && go build ./gpgme
  processing gpgme.yml done.
# github.com/proglottis/autogpgme/gpgme
could not determine kind of name for C.fnc

clang errors for preamble:
In file included from gpgme/cgo_helpers.go:9:
./cgo_helpers.h:14:75: error: unknown type name 'fnc'
unsigned int gpgme_register_io_cb_t_de500e8c(void* data, int fd, int dir, fnc fnc, void* fnc_data, void** tag);
                                                                          ^
1 error generated.
```

The `fnc fnc` argument has the wrong type.
